### ISSUE TITLE
extend FilterVariants to extract an arbitrary subset of positions or variants as listed in a file

### ISSUE THREAD

**Issue by jbloom22** [broadinstitute/hail#114]
We should extend filtervariants to take a file consisting of a list of positions (contig, start) or a list of variants (contig, start, ref, alt). In GoT2D, there are related .pos files of positions that pass various filters, and vcftools allows one to subset.

**Comment by cseed** [comment]
This is handled by `filtervariants intervals` and filtervariants list`.
