### ISSUE TITLE
Add dosage capability to Genotype class

### ISSUE THREAD

**Issue by jigold** [broadinstitute/hail#287]
The current BGEN implementation in Hail stores the dosage values as phred-scaled likelihoods (PLs). However, this results in a loss of information and we cannot filter genotypes on a particular maximum dosage (example: 0.8). Solution is to add functionality to the genotype class to store and handle dosage values natively.

**Comment by cseed** [comment]
Done: https://github.com/broadinstitute/hail/pull/573.
