### ISSUE TITLE
duplicated variants or intervals for annotations, what to do?

### ISSUE THREAD

**Issue by andgan** [broadinstitute/hail#451]
If there are duplicated variants or intervals in the annotation file, what to do?
1) Give the option to pick the first variant or interval and discard the rest. This makes sense in some scenario (for example the CADD file)
2) Create an annotation array that contains multiple annotations for a variants that was in multiple intervals.
cheers,

**Comment by cseed** [comment]
Do we need 2)?  If not, I'm going to close this issue.  The code has been doing 1) for a while.

**Comment by tpoterba** [comment]
Yeah, we do want 2).  Especially for intervals

**Comment by cseed** [comment]
I'm not convinced we want to do 2) for annotation by variant.

For 2), you want an option for `annotatevariants intervals`, when doing value annotation, to annotate with an array of values from intervals that contain the variant?  I'm OK with that.
