### ISSUE TITLE
inParX & inParY shouldn't be able to be 'true' for autosomes

### ISSUE THREAD

**Issue by ksatterstrom** [broadinstitute/hail#452]
As the docs state, inParX should be "true if in pseudo-autosomal region on chromosome X."  Likewise, inParY should be "true if in pseudo-autosomal region on chromosome Y."  However, these flags are currently being applied regardless of chromosome.

That is, currently any variant that meets (60001 <= start && start <= 2699520) || (154931044 <= start && start <= 155260560) gets inParX = true, and similarly for inParY.

This is confusing and, I would guess, in error.  inParX should only be able to be true if v.contig == "X" is true, and inParY should only be able to be true if v.contig == "Y" is true.

**Comment by jbloom22** [comment]
Addressed by #499
