### ISSUE TITLE
Error：Execution failed for task ':compileScala'

### ISSUE THREAD

**Issue by Sun-shan** [broadinstitute/hail#453]
Hello,when I build  Hail to run locally,I encounter this problem,how can I fix it ? 

[root@*** hail]# gradle installDist
Using a seed of [1] for testing.
Build file '/***/hail/build.gradle': line 188
useAnt has been deprecated and is scheduled to be removed in Gradle 3.0. The Ant-Based Scala compiler is deprecated, please see https://docs.gradle.org/current/userguide/scala_plugin.html.
:compileJava UP-TO-DATE
:compileScala
/***/hail/src/main/scala/org/broadinstitute/hail/driver/ExportVCF.scala:3: object time is not a member of package java
import java.time._
            ^
/***/hail/src/main/scala/org/broadinstitute/hail/driver/ExportVCF.scala:76: not found: value LocalDate
      sb.append(s"##fileDate=${LocalDate.now}\n")
                               ^
two errors found
:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Compilation failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 45.869 secs

**Comment by tpoterba** [comment]
duplicated with #454

**Comment by gilsonm** [comment]
Hi, I'm getting the same error trying to build Hail on Amazon Linux on an EMR cluster.
The suggested fix from issue #454 did not work.

To reproduce:

Clone hail from commit 6382678846a9c187d448713f26a2c38f21a683db
`$ gradle installDist`

**Comment by tpoterba** [comment]
I just tried cloned locally and `gradle installDist` worked on the first try.  We've gotten this compiler error sporadically for a few months, and every time it's been resolved by rebuilding after `gradle clean`.  I'll continue to investigate, and see if I can find the source of the problem (could be a compiler bug).

**Comment by gilsonm** [comment]
Hi, thanks for the quick response!

I updated the original post with more info to reproduce.
Please let me know if I can get you more information about the Scala environment!

All the best,
Michael

**Comment by tpoterba** [comment]
Hi Michael,
My mistake closing this in the first place -- I thought it was a duplicate issue in my morning haze, and never actually went back to read the full text when you commented.  The temporary solution is to use Java 8, but there's no reason we shouldn't use a backward compatible datetime library, so I'll open another issue for that.

Let me know if this fix works!

Tim

**Comment by gilsonm** [comment]
Hi, Tim

That did the trick. Thanks!

-Michael

**Comment by Sun-shan** [comment]
That did work, Thanks a lot ! @tpoterba
