### ISSUE TITLE
ERROR: org.broadinstitute.hail.annotations.AnnotationPathException,throw new AnnotationPathException()

### ISSUE THREAD

**Issue by Sun-shan** [broadinstitute/hail#454]
When buliding hail , There are several problems ，please help，thanks

[root@*** hail]# gradle shadowJar
Using a seed of [1] for testing.
Build file '/***/hail/build.gradle': line 188
useAnt has been deprecated and is scheduled to be removed in Gradle 3.0. The Ant-Based Scala compiler is deprecated, please see https://docs.gradle.org/current/userguide/scala_plugin.html.
:compileJava UP-TO-DATE
:compileScala
/***/hail/src/main/scala/org/broadinstitute/hail/expr/AST.scala:135: not enough arguments for constructor AnnotationPathException: (msg: String)org.broadinstitute.hail.annotations.AnnotationPathException
      throw new AnnotationPathException()
            ^
/***/hail/src/main/scala/org/broadinstitute/hail/expr/AST.scala:153: not enough arguments for constructor AnnotationPathException: (msg: String)org.broadinstitute.hail.annotations.AnnotationPathException
      throw new AnnotationPathException()
            ^
/***/hail/src/main/scala/org/broadinstitute/hail/expr/AST.scala:162: not enough arguments for constructor AnnotationPathException: (msg: String)org.broadinstitute.hail.annotations.AnnotationPathException
      throw new AnnotationPathException()
            ^
/***/hail/src/main/scala/org/broadinstitute/hail/expr/AST.scala:661: not enough arguments for constructor AnnotationPathException: (msg: String)org.broadinstitute.hail.annotations.AnnotationPathException
        case None => throw new AnnotationPathException()
                           ^
/***/hail/src/main/scala/org/broadinstitute/hail/expr/AST.scala:753: not enough arguments for constructor AnnotationPathException: (msg: String)org.broadinstitute.hail.annotations.AnnotationPathException
          throw new AnnotationPathException()
                ^
5 errors found
:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Compilation failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 39.537 secs

**Comment by tpoterba** [comment]
Run `gradle clean` before rebuilding, and everything will work!
