### ISSUE TITLE
Build FAILED:"gradle check"  AND "gradle coverage"

### ISSUE THREAD

**Issue by Sun-shan** [broadinstitute/hail#457]
I have build hail ,using "gradle installDist",  the "./hail -h" can display:

[root@*** bin]# ./hail -h
usage: hail [global options] <cmd1> [cmd1 args]
  [<cmd2> [cmd2 args] ... <cmdN> [cmdN args]]

But ,When  excuting  “gradle check” and "gradle coverage",  encounter "100 tests completed, 3 failed :test FAILED" "Build FAILED" , how to fix ? Thanks 

[root@*** hail]# gradle check
Using a seed of [1] for testing.
Build file '*****/hail/build.gradle': line 188
useAnt has been deprecated and is scheduled to be removed in Gradle 3.0. The Ant-Based Scala compiler is deprecated, please see https://docs.gradle.org/current/userguide/scala_plugin.html.
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestScala UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test

...........  FAILED
Gradle suite > Gradle test > org.broadinstitute.hail.methods.ExportPlinkSuite.testBiallelic FAILED
    java.io.FileNotFoundException at ExportPlinkSuite.scala:17
Running test: Test method test(org.broadinstitute.hail.methods.ExportSuite)
...........  FAILED
Gradle suite > Gradle test > org.broadinstitute.hail.driver.GRMSuite.test FAILED
    java.io.FileNotFoundException at GRMSuite.scala:20
Running test: Test method testGenotypeStream(org.broadinstitute.hail.variant.GenotypeStreamSuite)
...........  FAILED
Gradle suite > Gradle test > org.broadinstitute.hail.methods.ImputeSexSuite.testImputeSexPlinkVersion FAILED
    java.io.FileNotFoundException at ImputeSexSuite.scala:17
Running test: Test method test(org.broadinstitute.hail.variant.IntervalListSuite)

..........
100 tests completed, 3 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///****/hail/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9 mins 25.533 secs

**Comment by tpoterba** [comment]
These three tests call out to [Plink](https://www.cog-genomics.org/plink2).  If you install it from that link and add it to your global path, those tests will pass.  If that sounds annoying, you can trust that these tests pass on our end!

**Comment by Sun-shan** [comment]
@tpoterba 
Hi, Tim
I installed plink, and set the pathas follows,but when excute "gradle check",still have problems,I don't know how I should do ?
------------------(1) 
root **** $ plink --file test

@----------------------------------------------------------@
|        PLINK!       |     v1.07      |   10/Aug/2009     |
|----------------------------------------------------------|
|  (C) 2009 Shaun Purcell, GNU General Public License, v2  |
|----------------------------------------------------------|
|  For documentation, citation & bug-report instructions:  |
|        http://pngu.mgh.harvard.edu/purcell/plink/        |
@----------------------------------------------------------@

Web-based version check ( --noweb to skip )
......-----------------------------------------------------------------------------------
(2)  The path
export PLINK_HOME=/***/plink
export PATH=$PLINK_HOME:$PATH
----------------------------------------------------------------------------------------

(3) The errors:
Gradle suite > Gradle test > org.broadinstitute.hail.methods.ExportPlinkSuite.testBiallelic FAILED
    java.io.FileNotFoundException at ExportPlinkSuite.scala:17
Running test: Test method test(org.broadinstitute.hail.methods.ExportSuite)
Gradle suite > Gradle test > org.broadinstitute.hail.driver.GRMSuite.test FAILED
    java.io.FileNotFoundException at GRMSuite.scala:20
Running test: Test method testGenotypeStream(org.broadinstitute.hail.variant.GenotypeStreamSuite)
Gradle suite > Gradle test > org.broadinstitute.hail.methods.ImputeSexSuite.testImputeSexPlinkVersion FAILED
    java.io.FileNotFoundException at ImputeSexSuite.scala:17
Running test: Test method test(org.broadinstitute.hail.variant.IntervalListSuite)

**Comment by tpoterba** [comment]
Hi,
When I remove plink from my path I get a bit of a different error.  Can you rerun `gradle check` with the `--info` argument?  It'll vomit a bunch of details, but the output from those tests should tell us what's going on.

**Comment by Sun-shan** [comment]
@tpoterba 

Hi Tim ,Thank you for answering , I run the  "gradle check  --info" again , there is a lot of infomation, so I save the standard output and standard error in "check_info_1.txt",as attached. Thank you for your help


[check_info_1.txt](https://github.com/broadinstitute/hail/files/345679/check_info_1.txt)

**Comment by tpoterba** [comment]
I think I know the problem!  We are testing against Plink 1.9, but you have the old version 1.07 (which is my fault for linking the plink base page).   Install it from the link below and please try again:

[https://www.cog-genomics.org/plink2](https://www.cog-genomics.org/plink2)

**Comment by tpoterba** [comment]
For reference, here was the plink output from one of those tests:
```

    @----------------------------------------------------------@
    |        PLINK!       |     v1.07      |   10/Aug/2009     |
    |----------------------------------------------------------|
    |  (C) 2009 Shaun Purcell, GNU General Public License, v2  |
    |----------------------------------------------------------|
    |  For documentation, citation & bug-report instructions:  |
    |        http://pngu.mgh.harvard.edu/purcell/plink/        |
    @----------------------------------------------------------@

    Web-based version check ( --noweb to skip )
    Recent cached web-check found...Problem connecting to web

    Writing this text to log file [ /tmp/hail.3ouc7OzAKpSQ/plink.00001.log ]
    Analysis started: Mon Jul  4 11:38:41 2016

    ** Unused command line option: --vcf
    ** Unused command line option: src/test/resources/sample.vcf
    ** Unused command line option: --const-fid
```

**Comment by Sun-shan** [comment]
@tpoterba 
Hi Tim , thank you ,I tried the plink1.9, and it works. but when I use the "importvcf" command, there are some issues, I took the advice in "http://www.slf4j.org/codes.html",added one of the jars in my classpath,but the issue still appeared.

(1) command and the info:
root hail $ ./build/install/hail/bin/hail importvcf src/test/resources/sample.vcf.gz -f write -o sample_4.vds
hail: info: running: importvcf src/test/resources/sample.vcf.gz -f
hail: info: running: write -o sample_4.vds
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
hail: info: while importing:
    file:/***/hail/src/test/resources/sample.vcf.gz  import clean
hail: info: timing:
  importvcf: 736.849ms
  write: 2.463s

(2) modify the classpath
I add the "slf4j-nop.jar" in the CLASSPATH,as follows:
root hail $ echo $CLASSPATH
.:/usr/share/java/slf4j/slf4j-nop.jar:/opt/BioDir/jdk/jdk1.8.0_91/lib/dt.jar:/opt/BioDir/jdk/jdk1.8.0_91/lib/tools.jar

**Comment by tpoterba** [comment]
This SLF4J warning is nothing to be worried about -- we see that in our deployment here, and it doesn't affect the running or results in any way.  I'll create an issue to resolve this though.

Another note about running Hail: if you're running on one machine, using the script in `hail/build/install/hail/bin/hail` created by `gradle installDist` is the thing to do.  But if you're deploying on a spark cluster, you're going to need to do the following:

`gradle shadowJar` : this builds a jar in `hail/build/libs/hail-all-spark.jar`, which can be run in parallel using  the `spark-submit` command as below:

```
/usr/bin/spark-submit --executor-memory 48g --executor-cores 24 --class org.broadinstitute.hail.driver.Main ~/hail/build/libs/hail-all-spark.jar --master yarn-client <hail commands here>
```

**Comment by jbloom22** [comment]
Should this issue be considered resolved?
