### ISSUE TITLE
Auto-detect type in sample annotations (and maybe variant annotations)

### ISSUE THREAD

**Issue by mzekavat** [broadinstitute/hail#463]
In R, when you load a data table, it auto-detects whether each column is a character vs. numeric type.  It would be super if this could be implemented in Hail.  I'm guessing it would take the form of "if none of the fields in the column contain special characters or letters, then it's numeric, else it's character," (but maybe it's not so straight forward, not so sure...). 

Anyways, when you have over 30 annotations that are numeric, it's a bit of a pain to have to go through writing all the -t flag options in Hail, so if it could be auto-detected, that would be super!  

In the case where 'dummy' variables are used (like 1-5 for Batch), then the user should be able to say that that's a string or a "factor" as it is in R (or a character/string, which is essentially the same), for the purposes of analysis in linear regression.

**Comment by cseed** [comment]
Tim added impute.  Impute has some problems, continue discussion here: https://github.com/broadinstitute/hail/issues/520.
