### ISSUE TITLE
Code 'frozen' in second annotatevariants line: possibly infinite loop somewhere?

### ISSUE THREAD

**Issue by mzekavat** [broadinstitute/hail#490]
/mnt/lustre/tpoterba/bin/hail read -i file:///mnt/lustre/mzekavat/FinEst/FinEst.WGS.QCed_LipidSpecificPhenosv2.vep.vds --skip-genotypes \
annotatevariants expr -c 'va.transcript_canonicals = va.vep.transcript_consequences.filter(tc => tc.canonical == 1)' \
annotatevariants expr -c 'va.most_severe_csq = 
let x = va.transcript_canonicals.map(y => y.consequence_terms.toSet) in 
if (x.exists(tc => tc.contains("transcript_ablation"))) "transcript_ablation"
else if (x.exists(tc => tc.contains("splice_acceptor_variant"))) "splice_acceptor_variant"
else if (x.exists(tc => tc.contains("splice_donor_variant"))) "splice_donor_variant"
else if (x.exists(tc => tc.contains("stop_gained"))) "stop_gained"
else if (x.exists(tc => tc.contains("frameshift_variant"))) "frameshift_variant"
else if (x.exists(tc => tc.contains("stop_lost"))) "stop_lost"
else if (x.exists(tc => tc.contains("start_lost"))) "start_lost"
else if (x.exists(tc => tc.contains("transcript_amplification"))) "transcript_amplification"
else if (x.exists(tc => tc.contains("inframe_insertion"))) "inframe_insertion"
else if (x.exists(tc => tc.contains("inframe_deletion"))) "inframe_deletion"
else if (x.exists(tc => tc.contains("missense_variant"))) "missense_variant"
else if (x.exists(tc => tc.contains("protein_altering_variant"))) "protein_altering_variant"
else if (x.exists(tc => tc.contains("splice_region_variant"))) "splice_region_variant"
else if (x.exists(tc => tc.contains("incomplete_terminal_codon_variant"))) "incomplete_terminal_codon_variant"
else if (x.exists(tc => tc.contains("stop_retained_variant"))) "stop_retained_variant"
else if (x.exists(tc => tc.contains("synonymous_variant"))) "synonymous_variant"
else if (x.exists(tc => tc.contains("coding_sequence_variant"))) "coding_sequence_variant"
else if (x.exists(tc => tc.contains("mature_miRNA_variant"))) "mature_miRNA_variant"
else if (x.exists(tc => tc.contains("5_prime_UTR_variant"))) "5_prime_UTR_variant" 
else if (x.exists(tc => tc.contains("3_prime_UTR_variant"))) "3_prime_UTR_variant"
else if (x.exists(tc => tc.contains("non_coding_transcript_exon_variant"))) "non_coding_transcript_exon_variant"
else if (x.exists(tc => tc.contains("intron_variant"))) "intron_variant"
else if (x.exists(tc => tc.contains("NMD_transcript_variant"))) "NMD_transcript_variant"
else if (x.exists(tc => tc.contains("non_coding_transcript_variant"))) "non_coding_transcript_variant"
else if (x.exists(tc => tc.contains("upstream_gene_variant"))) "upstream_gene_variant"
else if (x.exists(tc => tc.contains("downstream_gene_variant"))) "downstream_gene_variant"
else if (x.exists(tc => tc.contains("TFBS_ablation"))) "TFBS_ablation"
else if (x.exists(tc => tc.contains("TFBS_amplification"))) "TFBS_amplification"
else if (x.exists(tc => tc.contains("TF_binding_site_variant"))) "TF_binding_site_variant"
else if (x.exists(tc => tc.contains("regulatory_region_ablation"))) "regulatory_region_ablation"
else if (x.exists(tc => tc.contains("regulatory_region_amplification"))) "regulatory_region_amplification"
else if (x.exists(tc => tc.contains("feature_elongation"))) "feature_elongation"
else if (x.exists(tc => tc.contains("regulatory_region_variant"))) "regulatory_region_variant"
else if (x.exists(tc => tc.contains("feature_truncation"))) "feature_truncation"
else if (x.exists(tc => tc.contains("intergenic_variant"))) "intergenic_variant"
else va.vep.most_severe_consequence' \
annotatevariants expr -c 'va.gene = 
if (va.transcript_canonicals.exists(tc => tc.consequence_terms.toSet.contains(va.most_severe_csq))) (va.transcript_canonicals.find(tc => tc.canonical == 1 && tc.consequence_terms.toSet.contains(va.most_severe_csq)).gene_symbol)
else (va.vep.transcript_consequences.find(tc => tc.consequence_terms.toSet.contains(va.most_severe_csq)).gene_symbol)' \
annotatevariants expr -c 'va.lof = 
if (va.transcript_canonicals.exists(tc => tc.consequence_terms.toSet.contains(va.most_severe_csq))) (va.transcript_canonicals.find(tc => tc.canonical == 1 && tc.consequence_terms.toSet.contains(va.most_severe_csq)).lof)
else (va.vep.transcript_consequences.find(tc => tc.consequence_terms.toSet.contains(va.most_severe_csq)).lof)' \
annotatevariants vds -i /user/satterst/atgu/dbNSFP_3.2a_HG19.vds \
-r va.dbNSFP \
annotatevariants expr -c 'va.of9 = (if ("D" ~ va.dbNSFP.SIFT_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.PROVEAN_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.Polyphen2_HDIV_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.Polyphen2_HVAR_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.LRT_pred) 1 else 0) + (if ("H" ~ va.dbNSFP.MutationAssessor_pred || "M" ~ va.dbNSFP.MutationAssessor_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.MutationTaster_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.FATHMM_pred) 1 else 0) + (if (va.dbNSFP.VEST3_score.str.split(";").map(v => v.toDouble).max >=0.75) 1 else 0)' \
annotatevariants expr -c 'va.LOF = (if (isDefined(va.andrea.lof)) 1 else 0), 
va.LOF_9of9 = (if (isDefined(va.andrea.lof) || va.of9 == 9) 1 else 0), 
va.LOF_8of9 = (if (isDefined(va.andrea.lof) || va.of9 >= 8) 1 else 0), 
va.LOF_7of9 = (if (isDefined(va.andrea.lof) || va.of9 >= 7) 1 else 0),
va.LOF_MetaSVM = (if (isDefined(va.andrea.lof) || ("D" ~ va.dbNSFP.MetaSVM_pred)) 1 else 0), 
va.Synonymous = (if (va.most_severe_csq == "synonymous_variant") 1 else 0), 
va.NonSynonymous = (if (va.most_severe_csq == "missense_variant" || va.most_severe_csq == "stop_gained" || va.most_severe_csq == "stop_lost" || va.most_severe_csq == "start_lost") 1 else 0)' \
write -o file:///mnt/lustre/mzekavat/FinEst/FinEst.WGS.QCed_LipidSpecificPhenosv2.vep.withGeneGroupingAnnot.vds
2 Comments C

**Comment by tpoterba** [comment]
fixed in dde9d5b
