### ISSUE TITLE
Why doesn't Jenkins delete workspaces for closed/resolved PRs?

### ISSUE THREAD

**Issue by danking** [broadinstitute/hail#655]
AKA: How can we avoid using Jenkins?

**Comment by danking** [comment]
On April 2016, this exact issue was reported: https://issues.jenkins-ci.org/browse/JENKINS-34177

This issue results in Jenkins using arbitrary amounts of disk space (until builds fail due to a full disk).

JENKINS-34177 was closed as a duplicate of: https://issues.jenkins-ci.org/browse/JENKINS-2111 which has been open since 2008. The thread of conversation seems to be about how difficult it would be to ensure that all files are deleted across all slaves. There have been no updates to that thread since October of 2015.

**Comment by danking** [comment]
TeamCity seems to have good [multiple feature branch support](https://confluence.jetbrains.com/display/TCD10/Working+with+Feature+Branches). However, it [requires](https://confluence.jetbrains.com/display/TCD10/Setting+up+an+External+Database) the use of an external database.

**Comment by danking** [comment]
We now have TeamCity running along side Jenkins at http://ci.hail.is:8111 . We'll test it out for a couple days and see if it represents a concrete improvement over Jenkins.

**Comment by cseed** [comment]
Not using Jenkins anymore.
