### ISSUE TITLE
Handling statistics computed from annotations

### ISSUE THREAD

**Issue by tpoterba** [broadinstitute/hail#89]
Something like call rate is trivially computable from `qc.nCalled` and `qc.nNotCalled`, but it's a pain to write the following on the command line to filter samples below 95% call rate:
`...filterSamples --keep -c "sa.qc.nCalled.toDouble/(sa.qc.nCalled+sa.qc.nNotCalled) > 0.95"`

We need another way to do things like this.

**Comment by cseed** [comment]
We added callRate to QC.  The current choice of computed values seems to be working.
