### ISSUE TITLE
Improved handling of sex chromosomes in MendelErrors

### ISSUE THREAD

**Issue by alexb-3** [broadinstitute/hail#91]
There are two types of sites at which males are hemizygous: X \ PAR and Y \ PAR (in the VCF the PARs are listed as part of X, so sites on Y are automatically non-PAR). The current code (modeled after PLINK) seems to treat only the first case correctly, checking the allele passed from the mother. In the second case one should check the allele passed from the father. Finally, any male could have a further kind of violation at a hemizygous site, namely a Het call; should we flag these as well?

**Comment by jbloom22** [comment]
Yes, PR #137 treats the hemizygous Y case as well.  As with Plink, I do not consider hets at homozygous sites to be Mendel errors, but rather sequencing errors. Users should deal with them separately as they see fit.
